### ISSUE TITLE
recognize problem

### ISSUE THREAD

**Issue by scutfrank** [k-m-irfan/microexpression_recognition#1] opened 2022-04-07 08:52 UTC
1.Labels do not change when changing facial expressions
2.The detection window will close automatically after running for a period of time

**Comment by k-m-irfan** [comment] 2022-04-07 11:10
1. Does it happen all the time? because the model was trained with a very small dataset, so it is not perfectly accurate and misclassifies sometimes.

2. Happened to me a couple of times. I have an old laptop and I thought this was happening because of it. Did you try with GPU?... Let me know how it goes.

**Comment by scutfrank** [comment] 2022-04-07 13:15
> 1. Does it happen all the time? because the model was trained with a very small dataset, so it is not perfectly accurate and misclassifies sometimes.
> 2. Happened to me a couple of times. I have an old laptop and I thought this was happening because of it. Did you try with GPU?... Let me know how it goes.

Thanks for your fast response !
1.I mean that if your face was detected at the first itme,it seems the lable will be fixed. For example ,if you make a expression happy ,then you turned to fear ,the label will remain happy even you change your expresion again and again at one time. Seems not the same as the introduction video ,perhaps about the background or the camera quality ?
2.It shows "Selected device: cuda" first then display  "INFO: Created TensorFlow Lite XNNPACK delegate for CPU." next line ,don't know what it means ,use tensorflow and cpu to run ? My laptop is CPU i7-11800(16G) and GPU rtx 3060(6G)

**Comment by k-m-irfan** [comment] 2022-04-07 16:32
1. I used an external camera. Try improving the lighting on your face if you are using the laptop camera or use a better external camera. You can also use your smartphone camera by using apps like droidcam or ip webcam. you just need to uncomment the below line and provide your device IP.
![image](https://user-images.githubusercontent.com/80172338/162246032-cee195a1-0f90-4fc9-afd8-8d12ff0affce.png)

2. "Selected device: cuda"... This is a good sign, this means your computer is using GPU for prediction.
"INFO: Created TensorFlow Lite XNNPACK delegate for CPU."...  This means mediapipe is running on CPU. Not a problem here.

Regarding the automatic closing of the window, I am looking into it. Meanwhile, If you find a solution feel free to post here or contribute.

**Comment by k-m-irfan** [comment] 2022-04-08 08:41
> 1. I used an external camera. Try improving the lighting on your face if you are using the laptop camera or use a better external camera. You can also use your smartphone camera by using apps like droidcam or ip webcam. you just need to uncomment the below line and provide your device IP.
>    ![image](https://user-images.githubusercontent.com/80172338/162246032-cee195a1-0f90-4fc9-afd8-8d12ff0affce.png)
> 2. "Selected device: cuda"... This is a good sign, this means your computer is using GPU for prediction.
>    "INFO: Created TensorFlow Lite XNNPACK delegate for CPU."...  This means mediapipe is running on CPU. Not a problem here.
> 
> Regarding the automatic closing of the window, I am looking into it. Meanwhile, If you find a solution feel free to post here or contribute.

I made some changes... check if it works for you

**Comment by scutfrank** [comment] 2022-04-08 09:29
> > 1. I used an external camera. Try improving the lighting on your face if you are using the laptop camera or use a better external camera. You can also use your smartphone camera by using apps like droidcam or ip webcam. you just need to uncomment the below line and provide your device IP.
> >    ![image](https://user-images.githubusercontent.com/80172338/162246032-cee195a1-0f90-4fc9-afd8-8d12ff0affce.png)
> > 2. "Selected device: cuda"... This is a good sign, this means your computer is using GPU for prediction.
> >    "INFO: Created TensorFlow Lite XNNPACK delegate for CPU."...  This means mediapipe is running on CPU. Not a problem here.
> > 
> > Regarding the automatic closing of the window, I am looking into it. Meanwhile, If you find a solution feel free to post here or contribute.
> 
> I made some changes... check if it works for you

Thanks for your effort ! Yes , it works. Now it will not automatically close the window.
But still the question: The label will not change even after I made a completely different and exaggerated expression in the laptop video. To exclude the cause of camera and ligth ,then I record the 1080P quality video by IP cam but the result is the same. Does it can real-time recognize the expression even you change your expression when you run it ?

**Comment by k-m-irfan** [comment] 2022-04-08 16:23
Would you mind sending the video to me so that I can check it on my system? Because although it misclassifies sometimes but works fine most of the time for me.

**Comment by scutfrank** [comment] 2022-04-09 04:24
> Would you mind sending the video to me so that I can check it on my system? Because although it misclassifies sometimes but works fine most of the time for me.
> 
> 

I have sent you the mail ,pls check.

**Comment by k-m-irfan** [comment] 2022-04-09 06:04
go it...

**Comment by k-m-irfan** [comment] 2022-04-09 06:39
> > Would you mind sending the video to me so that I can check it on my system? Because although it misclassifies sometimes but works fine most of the time for me.
> > 
> 
> I have sent you the mail ,pls check.

I updated the weights yesterday. But the video you sent works fine for both weights. Try to clean start once again, and if the problem is not fixed send me your code. Also, check if the package versions match. Check your mail for the labeled video.

**Comment by yangtaihong59** [comment] 2022-05-24 15:54
> > Would you mind sending the video to me so that I can check it on my system? Because although it misclassifies sometimes but works fine most of the time for me.
> 
> I have sent you the mail ,pls check.



> 1.Labels do not change when changing facial expressions 2.The detection window will close automatically after running for a period of time

Hi! I have the same problem 1. Did you find the reason？

**Closed as completed** 2022-07-13 17:37 UTC
